// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyjewxfosivqapndkfhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5amV3eGZvc2l2cWFwbmRrZmh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzQwMjgsImV4cCI6MjA2NzExMDAyOH0.zAVe-M56vKOFDBDxnWufZ0JvFJ0E0G_SJqQT7DpAhNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});